INSERT INTO jobs
    (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES ('IT_PROG', 'Programmer', 4000, 10000);

INSERT INTO jobs
    (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES ('MK_MAN', 'Marketing Manager', 9000, 15000);

INSERT INTO regions
    (REGION_ID, REGION_NAME)
VALUES (1, 'Europe');

INSERT INTO countries
    (COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES ('UK', 'United Kingdom', 1);

INSERT INTO locations
(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES (1000, '8204 Arthur St', null, 'London', null, 'UK');

INSERT INTO locations
(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES (1100, 'Magdalen Centre', '0X9 9ZB', 'Oxford', 'Oxford', 'UK');

INSERT INTO departments
    (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (10, 'IT', null, 1000);

INSERT INTO departments
    (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (20, 'Marketing', null, 1100);

INSERT INTO employees
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,
 JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (100, 'Steven', 'King', 'SKING', '022.237.221', to_date('2022/09/09', 'yyyy/mm/dd'),
        'IT_PROG', 9000, null, null, 10);

INSERT INTO job_history
    (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
VALUES (100, to_date('2021-10-09', 'yyyy/mm/dd'), to_date('2022-08-09', 'yyyy/mm/dd'), 'MK_MAN', 20);
